name: Check Links
on: [push, pull_request]

jobs:
  hypersweep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Validate Links using HyperSweep
        uses: DhanushNehru/hypersweep@main
        with:
          path: '.'
          workers: '100'
          timeout: '15'
